Repository ansible/workshops, pull requests merged in 2020-08, with the labels that each got.

#943 changing f5 image filter fix #940
  provisioner/roles/manage_ec2_instances/defaults/main/main.yml
Labels: f5-workshop

#941 Adding exercises for Ansible Collections
  exercises/ansible_collections/1-create-collections/README.md
  exercises/ansible_collections/1-create-collections/solutions/modules/demo_hello.py
  exercises/ansible_collections/1-create-collections/solutions/roles/demo_image_builder/.travis.yml
  exercises/ansible_collections/1-create-collections/solutions/roles/demo_image_builder/README.md
  exercises/ansible_collections/1-create-collections/solutions/roles/demo_image_builder/defaults/main.yml
  exercises/ansible_collections/1-create-collections/solutions/roles/demo_image_builder/files/Dockerfile
  exercises/ansible_collections/1-create-collections/solutions/roles/demo_image_builder/meta/main.yml
  exercises/ansible_collections/1-create-collections/solutions/roles/demo_image_builder/tasks/main.yml
  exercises/ansible_collections/1-create-collections/solutions/roles/demo_image_builder/templates/index.html.j2
  exercises/ansible_collections/2-collections-from-playbook/README.md
  exercises/ansible_collections/3-collections-from-roles/README.md
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_fqcn/.travis.yml
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_fqcn/README.md
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_fqcn/defaults/main.yml
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_fqcn/meta/main.yml
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_fqcn/tasks/main.yml
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_meta/.travis.yml
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_meta/README.md
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_meta/defaults/main.yml
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_meta/meta/main.yml
  exercises/ansible_collections/3-collections-from-roles/solutions/selinux_manage_meta/tasks/main.yml
  exercises/ansible_collections/4-collections-from-tower/README.md
  exercises/ansible_collections/5-use-automation-hub/README.md
  exercises/ansible_collections/5-use-automation-hub/screenshots/README.md
  exercises/ansible_collections/5-use-automation-hub/screenshots/copy-token.png
  exercises/ansible_collections/5-use-automation-hub/screenshots/create-token.png
  exercises/ansible_collections/5-use-automation-hub/screenshots/token.png
  exercises/ansible_collections/README.md
Labels: enhancement

#710 Make provisioner more compatible with running from tower
  provisioner/provision_lab.yml
  provisioner/roles/control_node/tasks/main.yml
  provisioner/roles/control_node/tasks/tower.yml
  provisioner/roles/manage_ec2_instances/tasks/resources/resources.yml
  provisioner/roles/manage_ec2_instances/tasks/teardown.yml
  provisioner/roles/workshop_check_setup/tasks/main.yml
Labels: provisioner
